### ISSUE TITLE
Bug when cpanm reports string missmatches between phases

### ISSUE THREAD

**Issue by kentfredric** [garu/App-cpanminus-reporter#11]
I was wondering why `BOBW/X86-Udis86-1.7.2.3.tar.gz` didn't send a report

```
Parsing /home/kent/.cpanm/build.log...
entering X86-Udis86-1.7.2.3, http://www.cpan.org/authors/id/B/BO/BOBW/X86-Udis86-1.7.2.3.tar.gz
left X86-Udis86-1.7.2.3, http://www.cpan.org/authors/id/B/BO/BOBW/X86-Udis86-1.7.2.3.tar.gz
Finished.
```

^^ Huh. Thats weird.

After looking through the parser, I find that its these lines having different strings that cause a failure:

Note: No `v`

```
Unpacking X86-Udis86-1.7.2.3.tar.gz
Entering X86-Udis86-1.7.2.3
```

...
Note: `v`

```
Configuring X86-Udis86-v1.7.2.3
...
Building and testing X86-Udis86-v1.7.2.3
...
Successfully installed X86-Udis86-v1.7.2.3
```

But the code in `reporter.pm` is looking for lines without the `v` for the `Building and testing` parts, so it entirely misses the data :( 

The cause is [this](https://metacpan.org/source/BOBW/X86-Udis86-1.7.2.3/META.json): 

``` json
 "version" : "v1.7.2.3"
```

This is correct per CPAN::Meta Specification.

However, `cpanm` reports the name of the tarball for the `Entering` statement, and uses the value of `version` from `META.json` from then on. 

This means you're essentially relying the whole tarballs name _exactly_ matching the distributions name + version, which is a somewhat flimsy assumption.

**Comment by garu** [comment]
I am pretty confident this was fixed but we forgot to close it, so I'm going to do it and if the error happens again with cpanm-reporter 0.19 please let me know and we'll work on it.
Thanks!
