### ISSUE TITLE
https scheme is not supported

### ISSUE THREAD

**Issue by karenetheridge** [garu/App-cpanminus-reporter#20]
`invalid scheme 'https' for resource 'https://cpan.metacpan.org/authors/id/E/ET/ETHER/Moose-2.1305-TRIAL.tar.gz'. Skipping...` :(

(possibly duplicate of #15)

**Comment by garu** [comment]
Fixed in #18! Sorry for not looking into this sooner, I'll ship a new release to CPAN later today!

**Comment by garu** [comment]
cpanm-reporter 0.12 just pushed to CPAN! Thanks for all the help!
