### ISSUE TITLE
metabase-profile exits without input

### ISSUE THREAD

**Issue by garfieldnate** [garu/App-cpanminus-reporter#32]
I ran cpanm-reporter --setup, and the part at the end didn't work so well:

    Would you like to run 'metabase-profile' now to create '/Users/nglenn/.cpanreporter/metabase_id.json'? [y]
    Running [/Users/nglenn/perl5/perlbrew/perls/perl-5.28.0/bin/metabase-profile --output /Users/nglenn/.cpanreporter/metabase_id.json --email garfieldnate@gmail.com --secret 74ccf154]...
    Enter full name:
    Writing profile to '/Users/nglenn/.cpanreporter/metabase_id.json'

The call to `metabse-profiler` exited with no input before I could type anything.

**Comment by garu** [comment]
Hi @garfieldnate! Thank you for the report and apologies for taking so long to reply. I am unable to reproduce this, is it still an issue?

I'll close the ticket but please reopen it if the issue persists for you.

Cheers!
