### ISSUE TITLE
Downstream breakage in CPAN-cpanminus-reporter-RetainReports (probably now fixed)

### ISSUE THREAD

**Issue by jkeenan** [garu/App-cpanminus-reporter#36]
This is not a bug report *per se*; rather, it is a report on how I dealt with breakage in a CPAN module that depends on `App-cpanminus-reporter`.

My CPAN distribution [CPAN-cpanminus-reporter-RetainReports](https://metacpan.org/pod/CPAN::cpanminus::reporter::RetainReports) (hereinafter, *C-c-r-R*) recently began to experience test failures as reported by CPANtesters.  See, for example, these [reports run against perl-5.36.1](http://fast-matrix.cpantesters.org/?dist=CPAN-cpanminus-reporter-RetainReports;perl=5.36.1;reports=1).  Andreas (@andk) diagnosed the cause of the failures as recent changes to prerequisite module App::cpanminus::reporter (hereinafter, *A-c-r*).

Ironically, the changes in the latter module that triggered the test failures appear to have come from a [pull request](https://github.com/garu/App-cpanminus-reporter/pull/29) I myself submitted more than five years ago and was recently merged, probably during the recent Perl Toolchain Summit.  So the wound was partially self-inflicted. ;-)

I originally wrote C-c-r-R when I was doing "CPAN River-style" testing of the Perl 5 core distribution.  That entailed installing a monthly development release, installing `cpanm` and C-c-r-R against that `perl`, then attempting to install 3000 CPAN distributions in a list pre-sorted to reflect CPAN dependencies (the "CPAN River").  C-c-r-R does not actually send a report to CPANtesters.  It saves the JSON report to disk where it can subsequently be analyzed for changes in PASS/FAIL status.  I wrote C-c-r-R such that it subclassed A-c-r, overwriting A-c-r methods as needed.  At the time I wrote C-c-r-R, the production version of A-c-r was 0.17.

I discontinued the CPAN River testing in 2020, IIRC, as the amount of new information it generated was not worth the machine and human time it took.  So at that point my need to actively maintain C-c-r-R lapsed and, for a variety of reasons, mainly used `Task::CPAN::Reporter` as my CPANtesters reporting tool.  As a consequence, these test failure reports for C-c-r-R caught me by surprise.  It took me some time to realize that:

* A-c-r's `get_author()` method now accommodated the `file` URI scheme.  Hence there was no longer need for a `get_author()` method in C-c-r-R that overrode the one inherited from A-c-r.

* But `get_author` still assumes that the path inside a `file` URI is constructed "CPAN-style", *i.e.*, `/M/ME/METATEST/tarball.tar.gz`, which in turn requires that dummy tarballs included in the distribution and used for testing need to be positioned in directories that reflect that convention.

I have created a [pull request for C-c-r-R](https://github.com/jkeenan/CPAN-cpanminus-reporter-RetainReports/pull/3) which I believe reflects these changes.  If you would like to take a look at that p.r., please do so (though I'm not requesting a formal code review).

Thank you very much.
Jim Keenan

**Comment by garu** [comment]
Hi Jim! Sorry for not replying sooner. Your PR looks ok, but I see now you've closed without a merge. 

And yes, `get_author` still assumes CPAN-Style subdirs. This is just to try and prevent people sending reports of patched versions or versions of distributions that are not on CPAN. I wanted to be extra conservative here because I think there could be a lot of potential for confusion if people submit reports for things they don't really want.

Thanks!
