### ISSUE TITLE
Test suite does not cover 3 URI schemes

### ISSUE THREAD

**Issue by jkeenan** [garu/App-cpanminus-reporter#37]
The code in `lib/App/cpanminus/reporter.pm` suggests that it is now capable of handling 5 different URI schemes:
```
   my %eligible_schemes = map {$_ => 1} (qw| http https ftp cpan file |);
```
However, the test suite only exercises 2 of these: `http` and `file`.  If you insert the following debugging statement into the module:
```
diff --git a/lib/App/cpanminus/reporter.pm b/lib/App/cpanminus/reporter.pm
index eb28667..872878c 100644
--- a/lib/App/cpanminus/reporter.pm
+++ b/lib/App/cpanminus/reporter.pm
@@ -467,6 +467,7 @@ sub parse_uri {
 
   my $uri = URI->new( $resource );
   my $scheme = lc $uri->scheme;
+print STDERR "SCHEME: $scheme\n";
   my %eligible_schemes = map {$_ => 1} (qw| http https ftp cpan file |);
   if (! $eligible_schemes{$scheme}) {
     print "invalid scheme '$scheme' for resource '$resource'. Skipping...\n"
```
... and then run `make test` and collate the output, you get the count for each scheme actually tested:
```
$ make test 2>&1 | grep SCHEME | cut -d ' ' -f2 | uniq -c
      1 file
     60 http
```
Now, I have to admit that I don't really know what the `cpan` scheme does, and my guess is that `https` works just like `http`.  So I don't know whether the lack of tests of 3 schemes is important or not.  Your call.

**Comment by garu** [comment]
Hi Jim! Thank you for letting me know. I've updated `t/18.parser.mixed_schema.t` to test against an https mirror and not regular (http) cpanmetadb. The other ones are supposed to be very rare, but let me know if you have a build.log with them and I'll patch the tests!
