### ISSUE TITLE
cpanm-reporter sends a single report then exits

### ISSUE THREAD

**Issue by genehack** [garu/App-cpanminus-reporter#39]
This is new behavior as of 5.38.0-RC1 or -RC2, I'm not sure which, but I've also just observed it on multiple machines while installing 5.38.0:

```
> plenv install-cpanm && cpanm App::cpanminus::reporter && cpanm Task::BeLike::GENEHACK
_many many MANY lines elided_
Successfully installed Task-BeLike-GENEHACK-0.402
416 distributions installed
sending: (http://www.cpan.org/authors/id/S/SH/SHANCOCK/Perl-Tidy-20230701.tar.gz, SHANCOCK, Perl-Tidy-20230701, PASS)
```

Exits with 0; running `cpanm-reporter` again does not send any additional reports. Observed on MacOS and Linux systems.

**Comment by garu** [comment]
Hi @genehack! Thanks for the report. cpanm-reporter only looks for build.log files that were last modified less than 30 minutes ago. Another possible reason is cpanm splitting into many different build.log files.

I was not able to reproduce the issue. Could you please try again with `cpanm-reporter --verbose --force`? If it still doesn't work, try `cpanm-reporter --verbose --force --all`?

Thanks!

**Comment by genehack** [comment]
> I was not able to reproduce the issue. Could you please try again with `cpanm-reporter --verbose --force`? If it still doesn't work, try `cpanm-reporter --verbose --force --all`?

Sure, I will try to reproduce during the 5.39.1 build I'll be doing soon, and let you know.

**Comment by genehack** [comment]
Just to update: `cpanm` is broken with 5.39.1, so I will return to follow up on this bug report when 5.39.2 ships.

**Comment by genehack** [comment]
And now that I have installed 5.39.2, I can no longer reproduce -- closing this out, sorry for the noise!

**Comment by garu** [comment]
Please don't hesitate to reopen or file any new issues if you spot them <3
