### ISSUE TITLE
error opening build log file

### ISSUE THREAD

**Issue by garfieldnate** [garu/App-cpanminus-reporter#8]
cpan-reporter dies with the following error:

```
error opening build log file 'C:\Users\Nathan\Desktop\strawberry-perl-5.18.1.1-64bit-portable\data\.cpanm\build.log' for reading: No such file or directory at C:\Users\Nathan\Desktop\strawberry-perl-5.18.1.1-64bit-portable\perl\site\bin/cpanm-reporter line 22.
```

I'm using Strawberry Perl Portable, 5.18.1.1. I zipped up my .cpanm folder (minus the sources folder) [here](http://uploadingit.com/file/view/aomwdta0tc1vlh6p/.cpanm.zip).

**Comment by garu** [comment]
Sorry for the very long wait. From the latest messages I'm assuming this was fixed upstream so I'm going ahead and closing the issue. Please let me know if it's still happening somewhere.
